### PR TITLE
Add #[repr(C, align(N))] to atomic types

### PR DESCRIPTION
**Pull request by taiki-e**
The doc says that atomic types and underlying types have the same in-memory representation.

https://github.com/pftbest/msp430-atomic/blob/da617ba1073c109cab68702a61da4d8b801d3aea/src/lib.rs#L79

However, the default layout of structs is not specified, so it must be of `repr(C)` type or `repr(transparent)` type with a precisely-defined layout to provide the above guarantees soundly. ([std atomic types are `repr(C)`](https://github.com/rust-lang/rust/commit/5e50acf443ecaad3f711780a62475e13c21e34ef))

refs:
- https://doc.rust-lang.org/nomicon/transmutes.html
- https://rust-lang.github.io/unsafe-code-guidelines/layout/structs-and-tuples.html#default-layout-repr-rust

### CODE REVIEW

**Comment by pftbest** [comment]
The code in this repo was copied "as is" from the rust standard library at the time. I'd like to keep it as close as possible to the stdlib, so maybe it's better to set #[repr(C, align(X))] instead of repr(transparent)? Unfortunately I don't understand it enough to know the difference in this case.

**Comment by taiki-e** [comment]
Sorry for the late reply!

> maybe it's better to set #[repr(C, align(X))] instead of repr(transparent)? Unfortunately I don't understand it enough to know the difference in this case.

In MSP430, u16 has the same alignment as the size, so in our case, the two mean the same thing.
However, I have recently learned that this is not the case in some architectures (at least AVR, u16's alignment is 1-byte).
So we should use `#[repr(C, align(X))]` here (otherwise calling atomic intrinsics will cause undefined behavior).
I'll update the PR.

**Comment by taiki-e** [comment]
Updated to use `#[repr(C, align(N))]`.

**Comment by pftbest** [comment]
Hello @cr1901, I think we can merge this, looks good to me.

**Review by cr1901 — APPROVED** [review]

**Comment by cr1901** [comment]
LGTM as well, thank you for waiting!

**Pull request merged**
